language: ruby
rvm:
- 2.7.0
env:
  global:
  - TRAVIS_NODE_VERSION="v8.9.4"
before_install:
- chmod +x ./.build_scripts/deploy.sh
before_script:
- ". $HOME/.nvm/nvm.sh"
- nvm install $TRAVIS_NODE_VERSION
- nvm use $TRAVIS_NODE_VERSION
- npm install -g gulp
- npm install
script: gulp prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: false
  on:
    branch: publish
  local_dir: _site
